include ../../lib/ct-verif.mk

goals += ssl3_cbc_remove_padding_wrapper@ssl3_cbc_remove_padding_wrapper.c
goals += ssl3_cbc_remove_padding_wrapper@ssl3_cbc_remove_padding_wrapper_error.c
goals += tls1_cbc_remove_padding_wrapper@tls1_cbc_remove_padding_wrapper.c
goals += ssl3_cbc_copy_mac_wrapper@ssl3_cbc_copy_mac_wrapper.c
goals += ssl3_cbc_digest_record_wrapper@ssl3_cbc_digest_record_wrapper.c
