include ../../lib/ct-verif.mk

goals += eccnorm_wrap@eccp2_wrap.c
goals += R1_to_R2_wrap@eccp2_wrap.c
goals += R1_to_R3_wrap@eccp2_wrap.c
goals += R2_to_R4_wrap@eccp2_wrap.c
goals += eccdouble_wrap@eccp2_wrap.c
goals += point_setup_wrap@eccp2_wrap.c
goals += ecc_point_validate_wrap@eccp2_wrap.c
goals += R5_to_R1_wrap@eccp2_wrap.c
goals += eccmadd_wrap@eccp2_wrap.c
#goals += ecc_mul_fixed_wrap@eccp2_wrap.c
