export ENTRYPOINT = sort3_wrapper

verify:
	EXAMPLE=${PWD}/sort.c make -C ../../bin verify

verify-negative:
	EXAMPLE=${PWD}/sort_negative.c make -C ../../bin verify

verify-multiplex:
	EXAMPLE=${PWD}/sort_multiplex.c make -C ../../bin verify
