export WD =${PWD}
export ENTRYPOINTS =sort3_wrapper

verify:
	EXAMPLE=sort.c make -C ../../bin verify

verify-negative:
	EXAMPLE=sort_negative.c make -C ../../bin verify

verify-multiplex:
	EXAMPLE=sort_multiplex.c make -C ../../bin verify
